// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cilvznmcnfpkkbmkuaep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpbHZ6bm1jbmZwa2tibWt1YWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTI1OTUsImV4cCI6MjA2NzY2ODU5NX0.8_ygaKkKdwk7i-WNyBX5gKGq3wE-uB_vAOzP6QkhYA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});